Repository codeit-6team/The-julge, pull requests merged in 2025-06, with the labels that each got.

#2 🎨 style: 초기 스타일 reset 및 스타일 변수 추가
  src/index.css
  vite.config.ts
Labels: 🎨 UI/스타일 관련

#12 ✨ feat: 각 페이지 컴포넌트 생성 및 라우팅 설정
  src/App.tsx
  src/index.css
  src/main.tsx
  src/pages/.gitkeep
  src/pages/account/Login.tsx
  src/pages/account/Signup.tsx
  src/pages/myprofile/Store.tsx
  src/pages/myprofile/StoreEdit.tsx
  src/pages/myprofile/StoreForm.tsx
  src/pages/myprofile/StorePost.tsx
  src/pages/mystore/Profile.tsx
  src/pages/mystore/ProfileForm.tsx
  src/pages/post/Post.tsx
  src/pages/post/PostList.tsx
  src/router.tsx
Labels: ✨ 기능 추가/구현, 📁 폴더구조 변경, 🐛 버그 수정

#28 🎨 style: index.css에 spacing 변수와 button cursor 스타일 설정
  src/index.css
Labels: 🎨 UI/스타일 관련

#26 ✨Feat: 드롭다운 컴포넌트 구현 및 드롭다운 아이템 상수 옵션 추가
  src/assets/icons/dropdown.svg
  src/components/common/Dropdown.tsx
  src/constants/.gitkeep
  src/constants/dropdownOptions.ts
Labels: ✨ 기능 추가/구현

#35 🎨 style: 그림자 효과 추가
  src/components/common/Dropdown.tsx
  src/index.css
Labels: 🎨 UI/스타일 관련

#37 ✨ feat: 알림 클릭 시 내 프로필 또는 내 가게 공고 페이지로 이동하는 기능 추가 및 코드 수정
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/notification-modal/NotificationCard.tsx
  src/components/common/notification-modal/NotificationModal.tsx
  src/context/.gitkeep
  src/context/AuthContext.tsx
  src/main.tsx
  src/utils/formatWorkTime.ts
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#42 🐛 fix: unit 값에 따라 선택 적용
  src/components/common/Input.tsx
Labels: 🐛 버그 수정

#40 🎨 style: middle size Button 컴포넌트 height 수정
  src/components/common/Button.tsx
Labels: 🎨 UI/스타일 관련

#53 ✨ feat: formatWorkTime함수에 잘못된 시간이 전달되었을 경우에 대한 예외 처리 추가
  src/components/common/notification-modal/NotificationCard.tsx
  src/components/common/notification-modal/NotificationModal.tsx
  src/utils/formatWorkTime.ts
Labels: ✨ 기능 추가/구현

#62 ✨ feat: alert용 api 파일 및 user용 api 파일 생성 및 타입 정의
  src/api/.gitkeep
  src/api/alertApi.ts
  src/api/userApi.ts
  src/constants/dropdownOptions.ts
Labels: 📁 폴더구조 변경

#67 ✨ feat: notice API 파일 생성 및 타입 정의
  src/api/noticeApi.ts
Labels: ✨ 기능 추가/구현, 📁 폴더구조 변경

#52 ✨ feat: Post 컴포넌트 구현
  src/assets/icons/arrow-up-gray.svg
  src/assets/icons/arrow-up-red20.svg
  src/assets/icons/arrow-up-red30.svg
  src/assets/icons/arrow-up-red40.svg
  src/assets/icons/arrow-up-white.svg
  src/assets/icons/clock-gray.svg
  src/assets/icons/clock-red.svg
  src/assets/icons/location-gray.svg
  src/assets/icons/location-red.svg
  src/assets/images/post-default.png
  src/components/common/Post.tsx
Labels: ✨ 기능 추가/구현

#71 ✨ feat: 회원가입 페이지 구현 및 타입 관련 수정
  src/api/alertApi.ts
  src/api/getAlerts.ts
  src/api/postToken.ts
  src/api/postUser.ts
  src/api/userApi.ts
  src/assets/icons/not-checked.svg
  src/components/common/notification-modal/NotificationModal.tsx
  src/context/AuthContext.tsx
  src/pages/account/Signup.tsx
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련, 📁 폴더구조 변경

#86 🐛 fix: Dropdown 컴포넌트의 z-index 추가
  src/components/common/Dropdown.tsx
Labels: 🎨 UI/스타일 관련, 🐛 버그 수정

#57 ✨ feat: filter 컴포넌트 구현
  src/assets/icons/close-red.svg
  src/components/common/Filter.tsx
  src/index.css
Labels: ✨ 기능 추가/구현

#87 ✨ feat: application API 파일 생성 및 타입 정의
  src/api/applicationApi.ts
  src/api/noticeApi.ts
Labels: ✨ 기능 추가/구현, ♻️ 리팩토링

#95 ✨feat: ImageUpload 컴포넌트 구현
  src/assets/icons/camera-gray.svg
  src/assets/icons/camera-white.svg
  src/components/common/ImageInput.tsx
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#104 🐛 fix: applicationApi link > links 수정
  src/api/applicationApi.ts
Labels: 🐛 버그 수정

#111 ✨ feat: shop API 함수 구현
  src/api/shopApi.ts
Labels: ✨ 기능 추가/구현

#115 ✨ feat: notice API 함수 구현 및 type 리팩토링
  src/api/noticeApi.ts
  src/components/common/Post.tsx
Labels: ✨ 기능 추가/구현, ♻️ 리팩토링

#110 ✨ feat: Table component 구현
  src/components/common/table/Table.tsx
  src/components/common/table/TableButtons.tsx
  src/components/common/table/TableStatus.tsx
Labels: ✨ 기능 추가/구현

#118 ✨ feat: RegisterLayout 컴포넌트 구현
  src/components/layout/RegisterLayout.tsx
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#126 🐛 fix: Post 컴포넌트 className Props 추가 및 고정 width 수정
  src/components/common/Post.tsx
Labels: 🐛 버그 수정

#127 ✨ feat: 알림 읽음 처리 구현
  src/components/common/notification-modal/NotificationCard.tsx
  src/components/common/notification-modal/NotificationModal.tsx
Labels: ✨ 기능 추가/구현

#131 ✨ feat: 공고 등록 (StoreForm) 페이지 구현
  src/pages/store/StoreForm.tsx
Labels: ✨ 기능 추가/구현

#129 ✨ feat: 내 프로필 상세 페이지 구현
  src/assets/icons/phone.svg
  src/pages/profile/Profile.tsx
  src/pages/profile/ProfileForm.tsx
  src/utils/formatPhone.ts
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#128 ✨ feat: 가게 페이지 (Store) 컴포넌트 구현
  src/pages/store/Store.tsx
Labels: ✨ 기능 추가/구현

#137 ✨ feat: PostLarge 컴포넌트 구현
  src/api/noticeApi.ts
  src/components/common/PostLarge.tsx
Labels: ✨ 기능 추가/구현

#140 ✨ feat: 사장님 공고 상세(StorePost) 페이지 컴포넌트 구현
  src/pages/store/StorePost.tsx
Labels: ✨ 기능 추가/구현

#148 🐛 fix: 알림 읽음 기능 수정 및 div 태그를 link로 수정
  src/components/common/notification-modal/NotificationCard.tsx
  src/components/common/notification-modal/NotificationModal.tsx
  src/components/layout/Navbar.tsx
  src/context/AuthContext.tsx
Labels: ♻️ 리팩토링, 🐛 버그 수정

#146 🐛 fix: Post 컴포넌트 내 div 태그를 link태그로 수정
  src/components/common/Post.tsx
Labels: ♻️ 리팩토링

#152 🐛 fix: Table Modal 오류 수정
  src/components/common/table/Table.tsx
  src/components/common/table/TableButtons.tsx
Labels: ♻️ 리팩토링, 🐛 버그 수정

#154 🐛 fix: 주소 옵션 순서 변경
  src/constants/dropdownOptions.ts
Labels: ♻️ 리팩토링

#156 🐛 fix: 검색 페이지 내에서 푸터가 뜨는 스타일 오류 수정
  src/pages/notice/NoticeList.tsx
Labels: 🎨 UI/스타일 관련, 🐛 버그 수정

#144 📝 docs: Readme 파일 생성
  README.md
Labels: 📝 문서 작업

#165 🐛fix: code splitting 및 404 페이지 구현
  src/App.tsx
  src/pages/error/NotFound.tsx
Labels: ✨ 기능 추가/구현, ♻️ 리팩토링
